binaries:
  - ruby-2.2.3
  - ruby-2.2.6
  - ruby-2.3.1
  - ruby-2.3.3
distributions:
  ubuntu_1204_64bit_precise: https://atlas.hashicorp.com/ubuntu/boxes/precise64/versions/20161208.0.1/providers/virtualbox.box
  ubuntu_1404_64bit_trusty: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20161214.0.0/providers/virtualbox.box
  ubuntu_1510_64bit_willy: https://atlas.hashicorp.com/ubuntu/boxes/wily64/versions/20160715.0.0/providers/virtualbox.box
  ubuntu_1604_64bit_xenial: https://atlas.hashicorp.com/ubuntu/boxes/xenial64/versions/20161221.0.0/providers/virtualbox.box
release_links:
  centos: http://en.wikipedia.org/wiki/CentOS#CentOS_releases
  debian: http://www.debian.org/releases/
  fedora: https://fedoraproject.org/wiki/Releases
  opensuse: http://en.opensuse.org/Lifetime
  ubuntu: https://wiki.ubuntu.com/Releases
image_links:
  - http://www.vagrantbox.es/
  - https://rvm_io.global.ssl.fastly.net/vboxes/
  - http://cloud-images.ubuntu.com/vagrant/
